### ISSUE TITLE
kicad libraries missing

### ISSUE THREAD

**Issue by bwack** [KimJorgensen/KungFuFlash#1]
Hi. Very interesting project. When I open the project in KiCad, it complains about missing symbol .lib files. Can you please share the `C64-Exp-Port.lib` and `KungFuFlash-rescue.lib` files ? The "??" symbol in the schematics points to the rescue library file (see properties) and KiCad did not find it. Thank you.

![Screenshot from 2020-01-03 11-18-37](https://user-images.githubusercontent.com/11380333/71718338-2c45fb80-2e1b-11ea-922e-0a6ab015e618.png)

I noticed later that the uSD_push-push_ebay:SD_ebay-uSD-push_push_SMD is also missing.

**Comment by KimJorgensen** [comment]
Yes, they were excluded by the .gitignore file. Let me know if it works now

**Comment by bwack** [comment]
Works great now. Thanks !

**Comment by KimJorgensen** [comment]
Sounds good. Thank you for reporting this
