### ISSUE TITLE
Recycling some hardware to make a frankenstien KungFu.....

### ISSUE THREAD

**Issue by pocoaust** [KimJorgensen/KungFuFlash#100]
G'day Mate,

love the project.  I have a micropython board that I want to recycle into a Kungfu board.  I have mapped all the hardware, but have one question.  Thes boards come with 12Mhz crystal onboard.  Is Kungfu capable of ruinning on this with a simple recompile without upsetting timeing, or should I swap the crystal.

**Comment by KimJorgensen** [comment]
You can try setting [PLL_M](https://github.com/KimJorgensen/KungFuFlash/blob/master/firmware/stm32f4xx/hal.h#L31) to 12 and recompile the firmware. For that I'm using GNU Arm Embedded Toolchain 9-2020-q2-update

**Comment by KimJorgensen** [comment]
Thanks and great that you got it running :)
