### ISSUE TITLE
Add support to Drean cartridge

### ISSUE THREAD

**Issue by beatmaster13** [KimJorgensen/KungFuFlash#101]
Hi there! Could you add support to Drean's Argentine-made cartridges?

http://www.compuclasico.com/site/user/pages/02.museo/01.commodore/g_gm_dc_02.jpg

You already have VICE support

https://sourceforge.net/p/vice-emu/code/39076/

https://sourceforge.net/p/vice-emu/code/40690/

ID:74

Attache:

https://send.cm/d/4lno

**Comment by KimJorgensen** [comment]
Hi,
It seems that the cartridge format is similar to Prophet64 and that it also can be used for emulate the Drean ones.
Do you know if a schematic of the cartridge exists or where to find more ROMs to test this?
/Kim

**Comment by beatmaster13** [comment]
Hi, Kim! Thanks for taking my inquiry

Everything I have

https://send.cm/d/4mHs

**Comment by KimJorgensen** [comment]
Thanks. Support for Drean cartridges has been added to relase v1.26

**Comment by beatmaster13** [comment]
Thank you very much for your support.
