### ISSUE TITLE
Does not start with Sound Expander cartridge

### ISSUE THREAD

**Issue by RobinArn** [KimJorgensen/KungFuFlash#108]
With the SFX Sound Expander cartridge in the C64, and the Kung Fu Flash inserted in the Sound Expander cartridge slot, the C64 will not start, a black screen comes up. Without the Kung Fu Flash, the C64 starts fine. Firmware v1.34

Kung Fu flash direct in the C64 works great, using 8GB SD (supplied with Kung Fu Flash), best product ever, will try it on Ultimate64 soon.

Best regards,
Robin
Amsterdam, The Netherlands

**Comment by KimJorgensen** [comment]
I guess this is due to a hardware conflict as both cartridges uses I/O2.
Firmware v1.36 and newer only uses I/O1 for the menu so that might work with the Sound Expander. However, emulating a cartridge that uses I/O2 (e.g. Action Replay or EasyFlash) will probably not work.
