### ISSUE TITLE
BOM mistake

### ISSUE THREAD

**Issue by djtulan** [KimJorgensen/KungFuFlash#11]
Hi!
In BOM there is a little mistake.

_Tactile Push Button Micro Switch - Use 6x6x6mm with TFW8b button caps or 6x6x9mm with 3.1mm A101 Plastic Switch Button Caps_

If somebody want to use the A101 Plastic Caps a 6x6mm with 10.5mm - 11mm height ist needed.

**Comment by KimJorgensen** [comment]
Thank you for reporting this. That should be fixed.

**Comment by djtulan** [comment]
The button height should be exactly 11mm. From the PCB to the top. I measured it again.

**Comment by KimJorgensen** [comment]
Thanks. I'll update the BOM with this.

**Comment by djtulan** [comment]
![a101](https://user-images.githubusercontent.com/1506204/80145262-3188ab00-85b0-11ea-915a-98f982d5df6d.png)

**Comment by KimJorgensen** [comment]
The BOM file has now been updated with the correct size of the push buttons.
Thank you.
