### ISSUE TITLE
KFF stuck at loading the same program (no menu)

### ISSUE THREAD

**Issue by germanviscuso** [KimJorgensen/KungFuFlash#110]
I was using KFF normally and loaded a program to test joystick ports. As usual, the program loads automatically but now the menu button just loads the same program.

I tried placing an empty microsd card but when I do that KFF enters a loop trying to load the missing program (menu doesn't work either).

Is this now a corrupted KFF? Can it be reset?
Interested to find out what triggered this behavior.

**Comment by KimJorgensen** [comment]
From your description, I have no idea if the flash is corrupted or what caused this behavior. However, if possible I would try the KFF with a different C64 to see if it does the same.

Should the flash be corrupt, it is possible to reinstall the firmware with the methods described here: https://github.com/KimJorgensen/KungFuFlash/blob/master/firmware/README.md

**Comment by germanviscuso** [comment]
Thank you Kim. Closing this ticket as I will try to reflash the KFF (might have been corrupted)
