### ISSUE TITLE
Reading TAPECART file

### ISSUE THREAD

**Issue by Mantics-68** [KimJorgensen/KungFuFlash#115]
Can .tcrt files be loaded with KUNGFU FLASH?

**Comment by KimJorgensen** [comment]
No, and it is would not work with the current Kung Fu Flash hardware.
Emulating a tapecart requires a physical connection to the cassette port

**Comment by mwedmark** [comment]
Ahh ok thanks! I though it was a specified file system format. I can see the problem! :-) Thanks for clearing that up!
