### ISSUE TITLE
C64 Game System mode

### ISSUE THREAD

**Issue by mwedmark** [KimJorgensen/KungFuFlash#116]
Suggestion for a new function:
- A settting under Kung Fu Flash settings called: "C64 Game System Mode" which shows an on-screen keyboard when doing search instead of waiting for key input.

**Comment by KimJorgensen** [comment]
Good idea. I guess this also requires the possibility to enter the settings menu and the search bar using the joystick

**Comment by KimJorgensen** [comment]
@mwedmark [FW 1.40](https://github.com/KimJorgensen/KungFuFlash/releases/tag/v1.40) now allows you to enter a search string with the joystick. Not exactly what you suggested, but I hope it will still be useful

**Comment by mwedmark** [comment]
From my point of view, you just nailed it! Perfect solution, even better than on-screen keyboard. Thanks!
I'm closing the issue as it is resolved.
