### ISSUE TITLE
Could we release Mac version of the EasyFlash tools?

### ISSUE THREAD

**Issue by mwedmark** [KimJorgensen/KungFuFlash#118]
A guy asked if he could use these tools on his Mac? Are there any Mac-users that could help us out?

**Comment by fortiko** [comment]
@mwedmark I have added some very small changes that allow the EasyFlash EF tools to be compiled on current versions of macOS and Apple Silicon that @KimJorgensen has incorporate in the main branch now: https://github.com/KimJorgensen/KungFuFlash/issues/165

**Comment by mwedmark** [comment]
Thanks for fixing and sharing!

**Comment by fortiko** [comment]
@KimJorgensen @mwedmark I think with the fixes in https://github.com/KimJorgensen/KungFuFlash/issues/165 we can close this as well? Not sure about providing binaries?

**Comment by magwed** [comment]
Yes I think you're correct, from my point of view that fixes it. Sorry to say, I'm not a Mac-person myself so this was mostly conveyed from friends/other users of Kung Fu Flash and probably not help with providing binaries.
