### ISSUE TITLE
Stability problems with replacement PLA's

### ISSUE THREAD

**Issue by patzik** [KimJorgensen/KungFuFlash#12]
With a (modern) replacement PLA, sometimes when mounting a d64 and loading a prg from it, either from menu of after a reset, the C64 comes with an error.
The errors I have seen are "out of memory", "drive not found"
Tested PLA's are:
DodgyPLA https://github.com/desaster/c64-dodgypla
MattisLind https://github.com/MattisLind/82S100replacement
PLAnkton

**Comment by KimJorgensen** [comment]
According to @dikdom KFF works fine with the PLA20V8 PLA replacement.

**Comment by KimJorgensen** [comment]
Could you please retest with version 1.09?
That version has been tested on my C64 ASSY #250407 with DodgyPLA, PLAnkton and J-PLA.

**Comment by patzik** [comment]
Tested with 1.09, works like a charm. Great work!!

**Comment by KimJorgensen** [comment]
Great, thanks for testing
