### ISSUE TITLE
Saving games in  Luftrauserz and 'Caren and the Tangled Tentacles'

### ISSUE THREAD

**Issue by mwedmark** [KimJorgensen/KungFuFlash#121]
I've tried out Easyflash3 releases of the games Luftrauserz and Caren and the Tangled Tentacles. The games worked fine but don't save their game data into the CRT when running when Kung Fu Flash. Am I missing how Saved games works on those games or is something missing? On f.e. Epyx Games Collection world records are correctly saved and restored automatically when using Kung Fu Flash. Has anyone got any of these games working with Easyflash3 CRT-save?

**Comment by KimJorgensen** [comment]
Which versions of LuftrauserZ and Caren and the Tangled Tentacles did you try, and have you tried testing these in VICE?

The original LuftrauserZ CRT release seems to be a Ocean type cartridge that only support saving to disk, and the newest release on CSDb says that high score save is disabled when using trainers.
