### ISSUE TITLE
Repurpose pins without losing functionality?  (question)

### ISSUE THREAD

**Issue by anonymouz** [KimJorgensen/KungFuFlash#133]
I've been playing around with the KFF pcb and layout and stuff (mostly learning, as I'm still a novice).

As far as I can tell the following pins are connected but the status of these pins could be deduced because all the address lines are available and-or the status of /GAME and /EXROM are known. Therefore I could repurpose these valuable pins for something else without losing functionality?   (still playing around with status output, LEDs and /DMA...)

/I/O1 (pin 7)
/I/O2 (pin 10)
/ROML (pin 11)
/ROMH (pin B)

My question; am I correct or is my understanding of these pins flawed?

Thanks for any help,
Onno

**Comment by KimJorgensen** [comment]
The address lines, /GAME and /EXROM are not enough to deduce the status of these pins. You would also need to know the status the CPU control lines that is used for bank switching, see https://www.c64-wiki.com/wiki/Bank_Switching and note that data written to the I/O register $01 of the 6510 CPU is not visible on the data bus.

If you need more pins then why not go for a MCU in a larger package?
