### ISSUE TITLE
[Support] Sidplay64 - access sid files

### ISSUE THREAD

**Issue by shelterx** [KimJorgensen/KungFuFlash#137]
First, excellent project and thanks for adding/fixing Sidplay64 support.
I don't have the kung fu flash cart yet but I will most likely buy one soon and I don't know where to ask this so pardon me if I'm posting in the wrong place.

I know I can probably put sidplay64 on a d64 image and put sid files on that image. But that limits the amount of sids i can have on each disk. naturally.
Is there any way to load sidplay64 with kung fu flash cart somehow and have it access a larger collection of sids?

**Comment by pmandes** [comment]
just use sidplay64-sd2iec version and browse the entire HVSC content on your SD card :)


![307433351_3283530985296599_3343733891288743543_n](https://user-images.githubusercontent.com/201662/191203773-8bb5e8d4-caa2-41ae-bb9a-e5d62c4be27a.jpg)


![308295592_416865537256718_6267256194887933649_n](https://user-images.githubusercontent.com/201662/191203828-4546b21b-3721-431b-be52-fd53cad25116.jpg)

**Comment by shelterx** [comment]
Very cool,  you for  your reply!
