### ISSUE TITLE
PC connection not working

### ISSUE THREAD

**Issue by sepa79** [KimJorgensen/KungFuFlash#140]
On 1.33 I can connect via ef3usb just fine, while on 1.39 and 1.43 the COM port dissapears from the Windows Device Manager as soon as I start es3usb or es3bbs program on C64.
I have not tested versions in between.

**Comment by KimJorgensen** [comment]
Possible duplicate of #132
Please see https://github.com/KimJorgensen/KungFuFlash/issues/132#issuecomment-1234381349

**Comment by sepa79** [comment]
Indeed it is a duplicate, and using Load method works. Sorry!
