### ISSUE TITLE
KFF doesn't detect microSD card

### ISSUE THREAD

**Issue by luke-70it** [KimJorgensen/KungFuFlash#144]
Hi, I bought KKF on ebay.
I send an email to the seller, but I opened this issue because I don't know if cartridge is defective or if I'm doing some mistake preparing sd...
I formatted a 16gb microSD card using FAT32, 4096 bytes.  For now I copied into it only firmware file (KungFuFlash_v1.43.upd) and I inserted it in KKF sd slot, but when I switch on my commodore64, KKF can't detect my sd card.
Is 16gb sd too big? Do I need to change format parameters or is my KKF not working correctly?

![KKF_alert](https://user-images.githubusercontent.com/54847115/196990498-b6fed9a9-e132-411f-a3a9-13a26511dc96.jpg)

**Comment by uffejakobsen** [comment]
What model/brand microSD card have you tried ? 
I had  problems with some no-name microSD cards from China (that worked well for other uses)

**Comment by luke-70it** [comment]
I tried with a 32gb HP card and with a 16gb Verbatim one.
Thank you for your support!!

**Comment by KimJorgensen** [comment]
This could very well be a hardware issue, but I think you should resolve this with the seller.
I have no problems with people selling Kung Fu Flash cartridges but they should also be willing to handle the support if something doesn't work

**Comment by gillham** [comment]
I would try a Sandisk or Samsung.  The Future Was 8-Bit sells the KFF with KIOXIA 16GB cards which seem to work great.

Just to confirm, you are pushing the card down until it clicks and is mostly flush with the top of the case? (if your unit has a case)  I guess it might depend on what kind of Micro SD socket that unit has, don't force it.
