### ISSUE TITLE
New game "Eye of the Beholder", and C128 2MHz -  problem

### ISSUE THREAD

**Issue by micv2** [KimJorgensen/KungFuFlash#151]
Hello,

there is a new awesome game that recognizes the 2MHz on the C128 (DCR). When I select 2MHz (F3) with KFF, 
the game crashes. The game works perfectly with an original EasyFlash.
Maybe you can fix the problem? 👍

Best regards, 
MiC

https://eotb64.com/
https://csdb.dk/release/?id=226060
https://www.forum64.de/index.php?thread/31235-released-eye-of-the-beholder/&pageNo=33

![IMG_3525](https://user-images.githubusercontent.com/45406373/203279703-75bad6e7-2faf-44f6-b17c-a38b7a1669f3.JPG)

**Comment by KimJorgensen** [comment]
You need to start the CRT in "VIC-II/C128 mode" to support 2MHz. This is done by using the file options menu (shift+return or long press fire).
However, KFF does not support flash save while in "VIC-II/C128 mode"
