### ISSUE TITLE
Multimax Cart image show bad graphics

### ISSUE THREAD

**Issue by mwedmark** [KimJorgensen/KungFuFlash#154]
This release:
https://csdb.dk/release/?id=210760&fbclid=IwAR1DVMMp6CKh0VKl65mG1n63pMGTbCT6NR9lAmlHjlPTChMHg1jNxmN_LYs

Ultimax Collection Crt. It is working as expected when mounted in VICE but show strange graphics on, at least, 2 different C64's.

According to comments the creator has created it especially for Easyflash/KFF and it "works" on v1.28 and higher?? Maybe not tested, that is not clear. I'll do some research and add info here about versions.

Screenshot of problem:
![20221216_193732](https://user-images.githubusercontent.com/2123085/208166426-f7a08732-171e-47be-a5d1-5a2cd109e47b.jpg)

**Comment by mwedmark** [comment]
v1.28 firmware has similar issues. Looks more of less the same.

**Comment by mwedmark** [comment]
https://www.lemon64.com/forum/viewtopic.php?t=74153

Seem to already have some problems with normal EasyFlash3. Should it work with KFF?

**Comment by KimJorgensen** [comment]
I guess that you need to start the CRT in VIC-II/C128 mode.
You can select that in the options menu (shift+enter or long press fire).

**Comment by mwedmark** [comment]
Thanks! never seen a Cart that needed that setting. Works as a charm!
