### ISSUE TITLE
C128D

### ISSUE THREAD

**Issue by AndreaMav** [KimJorgensen/KungFuFlash#156]
i have a 128d (cdr) with 1571 internal drive. The KFF works, but here are 2 problems found..
1- the .D64 MOUNT does not show the c64 basic screen, but returns to the classic menu with folder list
2- if I try to use SID files they are not recognized
3- if I try to use it even configuring the KFF as drive 9 it is still not seen.. if I try pressing F7 to exit the c64 basic screen and try to do a simple LOAD "$" ,9 I get the disk drive not error present

**Comment by KimJorgensen** [comment]
1. What do you mean by ".D64 MOUNT"? Did you select a .D64 file in the launcher and then choose "Mount" in the options menu (SHIFT+RETURN)?
2. Playing .SID files in the launcher is not supported (see #10). However, you can use sidplay64-sd2iec to play .SID files directly from the SD card
3. Pressing F7 will not enable the disk drive emulation. You need to mount a file or directory in the launcher, i.e. select a directory and used choose "Mount" in the options menu
