### ISSUE TITLE
Phi2 does not change

### ISSUE THREAD

**Issue by zitev** [KimJorgensen/KungFuFlash#159]
"..For reference the phi2 clock frequency should be around 985248 Hz for PAL.."
My phi2 frequency is fixed at 985212 and this value does not change even if I try to change it in a positive or negative direction. Otherwise, the change makes the machine unstable (so it works), but the displayed value remains constant (the card contains the latest firmware version).

**Comment by KimJorgensen** [comment]
Adjusting the phi2 clock offset does not change the phi2 clock frequency which is generated by the C64. You can adjust the frequency on most C64 motherboards with the variable capacitor or resistor close to the crystal. However, I would only recommend that if the frequency is way off or you can't get any color on the TV.

If you don't have stability issues I wouldn't change the phi2 clock offset
