### ISSUE TITLE
troubleshooting

### ISSUE THREAD

**Issue by dikdom** [KimJorgensen/KungFuFlash#16]
Hello,
a little help would be appreciated... 

So, PCBs arrived, most of the parts are pre-soldered. USB and SD slots, switches and jumper headers had to be soldered by me - done. Checked the USB slot with a cut USB cable, each wire is OK (+5V, GND, D- and D+, no shorts)

- firmware (v1.08) is uploaded ('Downloaded' in the terminology of dfu-utils) and read back ('Uploaded') and verified. It is OK. 

Q1: is it true that the computer should be able to see the board if I press all the three buttons at the same time? I have to press them at once in order win10 be able to see it.

Q2: no LED activity, when the board is connected to USB. Is it normal?

- OK, fw programmed, when I try it with C64, the LED is lit but the screen remains black. With an SD card, without an SD card.

I tested the SD slot's pins and they aren't shorted. 

Q3: Any idea where to start the debugging?

UPDATE#1:
A3: RN1 and RN2 is 10k resistor networks. Needs to be replaced, to be continued...

**Comment by KimJorgensen** [comment]
Hi,

Q1: There is no functionality that requires you to press all buttons at once. It may be necessary to press the reset button after shorting BOOT0 and +3.3V to make the microcontroller enter the built-in bootloader. When the bootloader is running the device should be detected by windows.

Q2: Yes, there is no LED activity when the bootloader is running.

Q3: If replacing the resistor networks doesn't help then try it with a different C64, preferably one with an original kernal and PLA.

**Comment by dikdom** [comment]
Thanks!

**Comment by rickard-von-essen** [comment]
@dikdom was this resolved by replacing RN1/RN2?

**Comment by dikdom** [comment]
@rickard-von-essen yes, it did the trick.
