### ISSUE TITLE
Functionality related question.

### ISSUE THREAD

**Issue by Gabeki17** [KimJorgensen/KungFuFlash#161]
Hi,

Actially I am having two.

1./ How can I create a directory using only my C64?

2./ What is the logic on the simulated drive presense?
Many times it is disapiring. (I might not understand the logic behind.)

Thx!
Really! :)

Gábor

**Comment by KimJorgensen** [comment]
1. There is no functionality for that
2. Disk emulation is active when a program is executed using the default option (RETURN) or a disk image or directory is mounted using "Mount" in the file options menu (SHIFT+RETURN)
