### ISSUE TITLE
Support for extra functionality to PS4-like remote reset

### ISSUE THREAD

**Issue by mwedmark** [KimJorgensen/KungFuFlash#164]
STM32 is already controlling the C64 reset line and the idea here would be to control the whole flow of:
- Choosing Game
- Starting Game
- Playing Game
- Resetting to menu

remotely without ever touching the C64. The idea is to being able to continuously choose/look for a particular combination of extended joystick buttons from Kung Fu Flash firmware and upon getting the correct value resetting the C64 and returning to Kung Fu Flash menu and being able to select a new game. Far fetch idea so I use this issue to ask if there is something stopping this.

**Comment by KimJorgensen** [comment]
I don't think this will be possible with the current hardware.
The additional joystick buttons needs to be read from the SID via the cartridge port, interrupting the running game at regular intervals. The KFF has no way of doing that (DMA line not connected) and even if it did, it may cause glitches or the game to crash.

However, it would be possible to create a small joystick adapter board with a wire to the menu button on the KFF
