### ISSUE TITLE
Did development stop?

### ISSUE THREAD

**Issue by Gabeki17** [KimJorgensen/KungFuFlash#167]
Hi,

Are there future plans might be?

Thx,
Gábor

**Comment by pigravity** [comment]
hope not.

**Comment by DWStaley** [comment]
If they're still supporting this project, it's a rather slow process. I submitted a new issue 6 weeks ago and still have no initial response from anyone.

**Comment by pigravity** [comment]
Would be very unfortunate and sad, there is alot of people now using KungFu and loving it, unless some other cart will take its place like SideKick or something, but still... I prefer KungFu :)

**Comment by ogg1e** [comment]
These people do this stuff on their own free time.  We're lucky this exists at all.

**Comment by KimJorgensen** [comment]
Development and answering support questions is done for free in my limited spare time. Feel free to fork this project and add features if you get impatient
