### ISSUE TITLE
How crucial are the values of R1, R5 and R6 resistors? (510R)

### ISSUE THREAD

**Issue by dburr** [KimJorgensen/KungFuFlash#169]
Putting together my Kung Fu Flash and have run into a bit of a snag. I don't have any 510R resistors for R1, R5 and R6. The only values close to that in my resistor kit are 470R and 560R. Can I substitute one of these for the 510Rs? Looks like R1 is a dropping resistor for the LED, so changing that resistor would only make the LED slightly brighter or dimmer, no big deal. But R5 and R6 seem to be a different story, they appear to be tied into the Menu and Special buttons in some way. (pull up/down?) Would changing these affect some sort of timing in some way? Forgive me if this is a noob question, I'm not hugely versed in the intricacies of digital electronics.

**Comment by KimJorgensen** [comment]
The actual value of R5 and R6 resistors is not that crucial as they act as a pull up. For R4 I'll go with 470R
