### ISSUE TITLE
Has anyone found a good Replacment or a good source for the STM32F405RGTx

### ISSUE THREAD

**Issue by SensoryTrash** [KimJorgensen/KungFuFlash#171]
anyone got any suppliers so many fake chippies around

**Comment by slawomir-krolik-maark** [comment]
I was also wondering if the MCU has to be so powerful, btw can be ordered from Mouser or Digikey

**Comment by dlxmax** [comment]
https://www.aliexpress.com/item/1005004638024448.html

**Comment by SensoryTrash** [comment]
Thank you
