### ISSUE TITLE
What is the thickness of the PCB?

### ISSUE THREAD

**Issue by SunnyIMG** [KimJorgensen/KungFuFlash#172]
as title

**Comment by KimJorgensen** [comment]
The standard PCB thickness of 1.6 mm should be used

**Comment by SunnyIMG** [comment]
thanks



---Original---
From: "Kim ***@***.***&gt;
Date: Thu, Jul 27, 2023 20:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [KimJorgensen/KungFuFlash] What is the thickness of the PCB?(Issue #172)




 
The standard PCB thickness of 1.6 mm should be used
