### ISSUE TITLE
D1 LED blinking rapidly after Firmware update attempt

### ISSUE THREAD

**Issue by funkychimp** [KimJorgensen/KungFuFlash#175]
Hi,

I purchased my KFF off fleabay. It worked fine. I then decided to update the firmware. I placed the firmware file on the SD and selected it. The device said it was flashing but then I got a garbled screen. I left it for a bit. Quite a while actually but it was obvious that the update had failed. Now when I restart the C64 I get a blank screen and the D1 LED just flashes rapidly.

Reading through some of the issues here I can see that my KFF looks to be bricked. So I purchased a STM32 ST Link programmer and connected to as detailed on the firmware page. The programmer finds the device and applies the firmware successfully. Yet on pluging the KFF back into my C64 I still get the same issue.  I think I am using the programmer correctly. I did not change any of its settings leaving them as default. I've taken screen shot of the programmer showing a successful flash.

Any help would be most appreciated.

Kind regards

Paul

![Screenshot 2023-09-06 205439](https://github.com/KimJorgensen/KungFuFlash/assets/6545928/82ca135c-7900-42bf-b61a-7f297743afdf)

**Comment by uffejakobsen** [comment]
It sounds as if your PHI2 clock is out of range...

My guess is that you firmware execution ended up here:
https://github.com/KimJorgensen/KungFuFlash/blob/66d5c63c84ed3556061848ed2751a7cc69916876/firmware/stm32f4xx/c64_interface.c#L306 

If your system works fine without the cartridge - it could be caused by bad connectivity...

You could try cleaning the cartridge connector on both cartridge and the port...

**Comment by uffejakobsen** [comment]
What firmware version did you install ?

While you are at it - you might try to downgrade to the version that it had before... it can't get any worse :-)

**Comment by funkychimp** [comment]
Hi, I'm not sure what Firmware it had on it before. It had a file on the supplied SD card called 'KungFuFlash v1.xx'.upd.  What ever version that was I don't know as I deleted it.

For the aviodence of doubt though. When you say firmware I assume you mean the upd file. If so then I flashed it with the latest 'KungFuFlash v1.47.upd' file. Changing the exe to .bin as instructed.

Regards

Paul

**Comment by KimJorgensen** [comment]
@funkychimp 'KungFuFlash v1.xx'.upd is some kind of unofficial release of the firmware. Given that and the blinking LED, could indicate that the microprocessor on the board is the unsupported GD32F405 (see https://github.com/KimJorgensen/KungFuFlash/issues/125). Maybe you can check that?

**Comment by funkychimp** [comment]
Hi Kim,

Yes you have nailed it. Looking at the chip it is a GD32. I have flashed the firmware from the fork and it's up and running again. Reading your comments on #125 I assume here that I will never be able to use your official FWs updates with my card. It's a shame the eBay seller was not more transparnat with the slight change to official spec.

In any case. I am glad it's now working. Thank you for your assistance and a great product.

Paul

**Comment by KimJorgensen** [comment]
Hi Paul,

The GD32 it is not fully compatible and I don't really want to deal with the extra testing effort and support of these. I also find it really annoying that people don't respect the spirit of the license and don't clearly state if they offer a modified version of Kung Fu Flash.

Anyway, glad you got it working again

Kim
