### ISSUE TITLE
No Effect trying to update.

### ISSUE THREAD

**Issue by rafael1138** [KimJorgensen/KungFuFlash#176]
Hi.

I have a KungFu Flash from Retrorewind with V1.44. I have downloaded the V1.47 and the system shows the upgrade menu and I selected Upgrade. After that I get a partial screen with the do not turn off message but inm half second returns to the main screen and the Versionat the botton still shows V1.44. I have tried V1.45 and V1.46 and the same issue.

**Comment by rafael1138** [comment]
Just want to add that the KFF is working with v1.44. Is just that is not allowing any update.

**Comment by KimJorgensen** [comment]
@rafael1138 I'm not sure why you can't upgrade the firmware but I think you should contact the seller with this issue.

I have no problem with people selling Kung Fu Flash cartridges, but they should also be willing to handle the support if something doesn't work
