### ISSUE TITLE
Did i brick it? (Solved by myself)

### ISSUE THREAD

**Issue by BlackHell666** [KimJorgensen/KungFuFlash#177]
I got my Kung-Fu Flash from TheFutureWas8Bit and it worked fine and i could update the firmware from 1.44 to 1.47.
Then i downloaded c64Dreams 0.60 with patch and i copied all D64 etc. to the included microSD Card.
I tried "To be on Top" and enabled the builtin Fastloader. But it didn't load well or i couldn't wait enough.
I wanted to return to the menu but i got the error message that the communication with the cartridge wasn't possible.
How can i make it work again?
I tried to connect USB with PC but without the Cartridge in C64.
I also couldn't find out which ports to connect to use ef3usb or to reset the complete Cartridge.
What should i do?

I don't know what happend but as soon as i pluged in the kung-fu-flash cartdrige in the C64 and used the usb connection to my PC and powered all on the cartdrige work perfectly as before.
Only the ef3usb com3 s didn't work and i don't know why. Maybe i'm also not patient enough.

**Comment by KimJorgensen** [comment]
Good that you got it working again.
Note that the disk drive emulation is [quite limited](https://github.com/KimJorgensen/KungFuFlash#limitations) and and will not work with fast loaders.

To use ef3usb on the PC you should first start the C64 and have the Kung Fu Flash menu running. Also, make sure COM3 is actually the port used for Kung Fu Flash
