### ISSUE TITLE
Cartridge dumper

### ISSUE THREAD

**Issue by beatmaster13** [KimJorgensen/KungFuFlash#180]
Hello Kim! I apologize for making this inquiry through this medium, but I didn't know how to contact you. 
Would it be feasible to create a cartridge dumper for Commodore similar to this one: 
https://krikzz.com/our-products/accessories/flashkitmd.html (SEGA)?

**Comment by uffejakobsen** [comment]
This is just one product out of many...
https://www.luigidifraia.com/hardware/#Commodore_64_Cartridge_Dumper

**Comment by beatmaster13** [comment]
Thank you very much for the information
