### ISSUE TITLE
Clarify instructions in ef3bbs.txt

### ISSUE THREAD

**Issue by IanSimpsonNZ** [KimJorgensen/KungFuFlash#181]
Can I start by saying a big thankyou to everyone involved in this amazing project.  I recently picked up a C64 and 1541, the Kung Fu Flash has served as a diagnistic ROM to get them up and running and now is showing me what I missed back in the 80's (I was a Spectrum kid).

A small suggestion - the txt file in the ef3bbs directory says that you need to be in the EasyFlash menu for ef3bbs to work.  This may be true for the EasyFlash, but isn't right for the KFF - you need to be in the KFF menu for the usb serial port to work.  This may be obvious for most people, but I've just spent a couple of evenings swapping usb cables and checking my linux distro config because I wsn't getting a  connection even though I carefully followed the instructions and left the KFF at the EF menu.  Yes, I know, I'm not very bright.

Thanks again.

**Comment by KimJorgensen** [comment]
Thank you.
Yes, the documentation could be better. If you want to help, feel free to make a pull request with the changes

**Comment by IanSimpsonNZ** [comment]
Done - hopefully.  First attempt at a pull request.
