### ISSUE TITLE
Insert SD-card issue 

### ISSUE THREAD

**Issue by sonkite** [KimJorgensen/KungFuFlash#183]
I have recently ordered 10 KFF v2 from jlcpcb.
Mounted all the components and flashed successfully with 1.48.

It works fine - for a while.... for all of them!

After that, like 30min plus, it says "insert fat formatted sd card".
Same issue for so far all of them except one, i think... havent fully tested all.

If i switch sdcard it doesnt help. 

After issue presented it comes back earlier next time...
Exchanged sdcard reader on one.. 

Any suggestions? All 10 cant be faulty i presume...

Tested on 2 different c64c.
Testef 2 different sdcards.

Thanks in advance 
Johan

**Comment by KimJorgensen** [comment]
Hi Johan

Let me see if I understand what is happening: After using the Kung Fu Flash cartridge for 30+ minutes then it won't read the SD card anymore.
But then what? You reset the cartridge and it works again? Or you power off the C64 and it works again? Or the sdcard is totally dead and won't work again, but a new sdcard will until that also dies after 30+ minutes?

**Comment by sonkite** [comment]
Sorry for being unclear.

It works for 30min.
After that it doesnt detect the card anymore.
Doesnt matter if I reset etc....only thung that helps it cooling off.
Sdcard works fine if I put it in the computer or another kff cart.

Same issue with all my 10 build kff carts.

Seems like some component is weakening with heat / current and I dont know where to look. Seems wierd that all 10 has the same issue.

Tested 2 different sdcards, 10 kff selfbuild (from same batch).

First test of a kff cart, it works for lika 30-60min.
After that it works less for every time, after some hours of cooldown

Tested 2 different c64c. Same problem so I dont think its the computer.

KFF diagnostics says Clock frequency at 985220.

Dont know where to look for failures. Some soldering? Some weak components?

**Comment by KimJorgensen** [comment]
I have never experienced anything like that, and none of the components on the Kung Fu Flash cartridge seems to get hot at all.
Have you tried with a different power supply?

**Comment by sonkite** [comment]
I have 1 original PSU (Light Grey version) and 1 brand new modern switched PSU. Tested both, same issue.

I have now made a new rest.
2/8 KFF works perfectly for 2h+.
6/8 KFF fails within 1,5h. After cooldown (waited like 3h, didnt check earlier) works again but eventuelly fails again within the same timeframe.

Tested them with same 2 sdcards, both computers, both PSU - no pattern as i can see.

I have replaced sdcard reader on 1 but sadly left it at work for the holidays so cant test it...

Sdcard reader bought at Aliexpress, weak quality?

Any soldering i should check except for the obvious ones at the cardreader? :)

Merry christmas,
Johan

**Comment by pmandes** [comment]
Check the voltage drop after heating on the LDO, whole faulty batches happen. Show a photo of your boards. Reflow MCU will not hurt if it is a cold solder issue.

Best
Pawel

**Comment by sonkite** [comment]
Thanks for your answers, both of you :)

Here comes the pictures.
I will try to measure tomorrow and reflow mcu.

![20231226_214447](https://github.com/KimJorgensen/KungFuFlash/assets/84403899/3bf63aa7-ed34-47ed-89f6-421e19d9e0ac)
![20231226_214505](https://github.com/KimJorgensen/KungFuFlash/assets/84403899/c1ea5825-535c-4d27-b36f-628f3a657366)
![20231226_214529](https://github.com/KimJorgensen/KungFuFlash/assets/84403899/ae8c6ccf-4c32-44e0-8da2-b147a83a1a4b)
![20231226_214559](https://github.com/KimJorgensen/KungFuFlash/assets/84403899/a4ff66ee-2bf7-4459-876a-8b8e671426d0)
![20231226_214609](https://github.com/KimJorgensen/KungFuFlash/assets/84403899/4c1f46af-441c-461d-8678-8bcd0e22b8eb)
![20231226_214711](https://github.com/KimJorgensen/KungFuFlash/assets/84403899/39645331-8390-4df0-86a5-a031b69c2d68)
![20231226_214725](https://github.com/KimJorgensen/KungFuFlash/assets/84403899/3a4877cb-07a4-4ae2-a9b4-af0989d3eac8)
![20231226_214731](https://github.com/KimJorgensen/KungFuFlash/assets/84403899/eab294da-62aa-4657-9ace-0ee9e8a6177b)

**Comment by sonkite** [comment]
Now measured U2.
From C64        After regulator U2
5.03V              3.31V       -- at start up
5.05V              3.31V       -- when failing the sdcard

"Right side of C2" - 3,31V
"Right side of C4" - 3,31V

**Comment by UffeJakobsen** [comment]
Are the SDcards getting hot ?
Your test description does not tell if you also let the SDcard rest for hours before testing another unit ?
I come across some (fake?) sdcards that got extremely hot and eventually stopped working... the would seem work again after cooling down...

**Comment by sonkite** [comment]
Its the same two SD-cards im using.
Dont let them cooldown and problem is not that since it works in another KF.

It might be the SD-card readers, have noticed that strange behaviors... tried to resolder and works temporarily sometimes. Tried to replace and got better before worse again (readers from the same batch).

I have ordered new readers but takes like a month...

**Comment by CqaZ80** [comment]
rinse with white benzine for 1 hour ( into a glass container) and clean with a toothbrush from time to time... I got some strange behavior pretty similar to you, some flux remains can do some problems if you don't clean enough.

**Comment by sonkite** [comment]
Thanks for your reply.

I've washed in ipa (isopropyl alcohol) and tried to reheat the connections... i will try another bath for one of the cards :)

**Comment by sonkite** [comment]
Update:
It got better with 4h ipa bath and cleaning with a toothbrush every 30min :)
It was probably not enough with my first cleaning which i thought was very carefully.
