### ISSUE TITLE
Feature request: Hide files/folders that have hidden attribute set

### ISSUE THREAD

**Issue by buzbard** [KimJorgensen/KungFuFlash#184]
Nice little cartridge, I like it!

It would be nice if files and folders, that have the hidden attribute set, to not show up in the menu.

Reason: WIndows has a nasty habit of adding a "System Volume Information" folder to all usb and sd-cards.

Plus it would be nice to hide some PC tools and such on the memory card.

Thanks...

**Comment by KimJorgensen** [comment]
Yes, this is a nice addition. It is added to the [latest release](https://github.com/KimJorgensen/KungFuFlash/releases/tag/v1.49), thanks

**Comment by buzbard** [comment]
Wow, fast reply. It works great, thanks!
