### ISSUE TITLE
Change device number? 

### ISSUE THREAD

**Issue by FunctionalHacker** [KimJorgensen/KungFuFlash#186]
There is a reference to changing device number here https://github.com/KimJorgensen/KungFuFlash/releases/tag/v1.41 but I didn't find any documentation on how to actually do it.

**Comment by KimJorgensen** [comment]
You can change the device number in the settings menu (F5). The function keys are documented in the help screen (F1)

**Comment by FunctionalHacker** [comment]
Thank you! Excuse my ignorance, just starting out with retro computing
