### ISSUE TITLE
ef3usb not working with firmware 1.49 on C128D

### ISSUE THREAD

**Issue by jperrin72** [KimJorgensen/KungFuFlash#189]
Since I upgraded firmware to v1.49, ef3usb fail into sending data to my c128d (ef3usb com4 s or ef3usb com4 0). I downgraded to v1.48 and got it working again. I have check that serial port etc where correct with latest firmware. Please let me know if you need anything from me to fix. Thanks

**Comment by KimJorgensen** [comment]
Thank you for reporting. Fixed in v1.50

**Comment by jperrin72** [comment]
Awesome - Thank you Kim 🤩
