### ISSUE TITLE
Prince of Persia garbled screen with C128 and Kung Fu Flash

### ISSUE THREAD

**Issue by tomnic79** [KimJorgensen/KungFuFlash#190]
Hi, I cannot run Prince of Persia with my King fu Flash and my C128, all I can get is a totally garbled screen after the easyflash loading screen and selecting start to play the game.

Sam's Journey, Super Mario Bros, A pig quest all work beautifully! Tried every updated firmware till 1.50 but same issue here.

Is my C128 faulty?

**Comment by KimJorgensen** [comment]
Please see https://github.com/KimJorgensen/KungFuFlash/issues/148#issuecomment-1310513219
