### ISSUE TITLE
Transferring one file from a 1541 disc to the SD Card in a KFF

### ISSUE THREAD

**Issue by lozknowles** [KimJorgensen/KungFuFlash#191]
Hi is there an easy way of transferring an individual SEQ file of assembler code from a 1541 to the SD card in the KFF?

**Comment by KimJorgensen** [comment]
This is related to #188 

It is possible if the Kung Fu Flash drive emulation is active on a different device number than your external 1541 (see settings F5) **and** you can find a program that can copy SEQ files using kernel vectors.

If no such program can be found, you can write one in BASIC to copy a SEQ file from one drive to another
