### ISSUE TITLE
Can't use menu button or reset buttons properly

### ISSUE THREAD

**Issue by hatchlof** [KimJorgensen/KungFuFlash#193]
I have a NTSC C64 with Motherboard ASSY 326298 Rev A. I have not been able to use the menu or the reset keys on the kung fu flash cartridge. They just cause the screen to glitch out and the system to freeze.

My kung fu flash behaves like the following:

With no kungfuflash.dat on the sd card when I boot the system, I am given the list of crt files on my sd card.

If I choose one of the crt files, the screen then goes black and nothing happens.

After this, I will reboot and the system will just boot up to the last selected game without going to the menu.

I can play through whatever game loads with no issues or glitches at all. everything works fine within the game.

If I try hitting the menu button on the cartridge to back out of this, the system then just freezes. same thing with the reset button.

The only way for me to get back to the main menu is to remove the sd card, go back to my computer and delete the kungfuflash.dat file.

I have tried multiple different firmware versions with the same results.

I have also tried using the diagnostics option to increase or decrease the phi offset which seems to change behavior only slightly. It either still glitches or if I go too far in either direction it'll just boot to the default blue C64 boot screen. Also, because the menu button causes the screen to glitch, I can't see what's happening while in the diagnostic mode. (I'm not sure I'm supposed to be able to)

I have read through many other previous issues and tried things like cleaning all the contacts in the cartridge and addon on slots on my board

I would love to know any other methods I could use to try to resolve this.

**Comment by KimJorgensen** [comment]
This issue is not possible to fix with the current Kung Fu Flash hardware, but requires a mod to the C64 motherboard.
I'll close this issue as wontfix
