### ISSUE TITLE
Mega65 C64 Core, odd Phi2 values

### ISSUE THREAD

**Issue by Kugelblitz360** [KimJorgensen/KungFuFlash#195]
Good morning. The KFF is working MOSTLY, some cartridges like Super Snapshot do not. I tried the diagnostic tool and am getting odd Phi2 values which do not change when I add an offset so I guess the offset is not a 1:1 relation.

When the C64 core is in "Flicker Free Mode" (machine slowed down slightly to lock precisly on 50 Hz), Phi2 is measured at 982756. In this mode, most freezer cartridges will not come up on standard machine reset. FC3 will work after a Reset on the KFF, but has some flicker in the characters which goes away immediately when switching off Flicker Free Mode.

When the C64 core in NOT in "Flicker Free Mode" Phi2 is measured at 985218. FC3 works as it should. Super Snapshot still does not work.

What is your suggested Phi2 offset for these scenarios? Thank you!

**Comment by KimJorgensen** [comment]
The Phi2 clock is generated by the C64 hardware and is not affected by the Phi2 offset in any way.

The KFF uses the Phi2 clock to know when to read the address bus, the control signals etc. Adjusting the offset will change when to read these signals.

Note that the KFF is not a precision instrument and variations between two different cartridges can be expected, see https://github.com/KimJorgensen/KungFuFlash/issues/89#issuecomment-923126640

So if the Phi2 clock is off you need to fix that in the Mega65 C64 Core

**Comment by Kugelblitz360** [comment]
Yeah - issue is under discussion over there. Question is if you have a suggestion on setting the offset with the values I posted.

Thanks, Boris!

**Comment by KimJorgensen** [comment]
There is no relationship between the phi2 clock frequency and the phi2 offset a C64 may require. It is dependent on the timing requirements of the hardware in the specific C64.

Sorry but I don't own a Mega65 so I can't offer you much advise. You can try increasing or decreasing the offset by one at a time, but I don't know if adjusting the offset would even solve your problem

**Comment by Kugelblitz360** [comment]
The root cause was something totally different: The combination of JaffyDOS, KFF and the Mega65 does not work properly. Switching to original JiffyDOS all problems go away.
