### ISSUE TITLE
Saving game process 

### ISSUE THREAD

**Issue by mauiphill** [KimJorgensen/KungFuFlash#211]
Can anyone tell me how to save game progress on the Kung Fu Flash 2 please.

**Comment by KimJorgensen** [comment]
Kung Fu Flash does not have a general save state feature. However, it can emulate freezers like Action Replay or Super Snapshot. Writing to flash is also supported for EasyFlash CRT releases (#8).

I'll close this issue as a duplicate of #46 and #178.
