### ISSUE TITLE
Sorted directory list

### ISSUE THREAD

**Issue by dikdom** [KimJorgensen/KungFuFlash#23]
Hello! Would it be possible somehow to order the directory list alphabetically? And always put the directories in the beginning of the list?
Currently it is listed as one wrote to the SD card. Sometimes it is hard to find a title.

**Comment by KimJorgensen** [comment]
No sorting has been implemented in KFF as this would make the navigation really slow for large directories. However, CapFuture1975 on forum64 suggested that you can use a tool on the PC to sort the files on the SD card.
http://www.anerty.net/software/file/DriveSort/

**Comment by dikdom** [comment]
What is the STM32 side retrieves the full directory (if it fits into its memory) and sorts it.. That could be processed fast.

**Comment by KimJorgensen** [comment]
Large directories won't fit in the available memory and that is why sorting would be really slow.

**Comment by dikdom** [comment]
Ok, thanks!

**Comment by jmredfern** [comment]
@KimJorgensen what about the STM uses a paging file as virtual ram on the sdcard to do the sorting? just a thought, thanks for the cart!
