### ISSUE TITLE
rev2 built, tested, works

### ISSUE THREAD

**Issue by dikdom** [KimJorgensen/KungFuFlash#25]
Hello,
HW rev2 board has been built, and tested.
SMT production files at JLCPCB are attached as a zip (excluding USB and microSD sockets and tack switches). Feel free to use it. 
[KungFuFlash-rev2-JLCPCB-smtproduction.zip](https://github.com/KimJorgensen/KungFuFlash/files/4844822/KungFuFlash-rev2-JLCPCB-smtproduction.zip)

The lower side of the printed case is just fine, the upper side needs some rework because of the usb socket. I can attach some images later if you'd need some.

**Comment by KimJorgensen** [comment]
Yes, I did also just finish assembling my rev. 2 boards and they works fine.
Thank you for testing and the SMT files which I attached to the release.
