### ISSUE TITLE
Find a KungFuFlash

### ISSUE THREAD

**Issue by danko79** [KimJorgensen/KungFuFlash#27]
Hi,and sorry for the issue open, i am looking for a pcb rev 2 do you have a one cartridge for sale?

**Comment by KimJorgensen** [comment]
Sorry, no.
You could try the marketplace on forum64.de or amibay for such requests

**Comment by rickard-von-essen** [comment]
@danko79 drop me an email.

**Comment by danko79** [comment]
Mail send.

**Comment by danko79** [comment]
> @danko79 drop me an email. 

Mail send. Thanks
