### ISSUE TITLE
magic desk 1024 carts issue

### ISSUE THREAD

**Issue by Braincell1973** [KimJorgensen/KungFuFlash#32]
Hi, 

I just assembled a kungfuflash and i love it but i tried a 1024mb crt file that i made for a physical magic dsk 1024k  cart and although the menu works the games do not ???

I used cartconv to test in vice with no issues.

Is there a size limit on the supported magic desk format ?

Lee

**Comment by Braincell1973** [comment]
Hi Kim,
             Thank you for the reply, I do not know if there are any publcally available 1024k images so im attaching 2 that i have made to this email.

These work fine in vice 3.4 and the bin files were successfully used to make physical carts so i am fully confident the code is good.

Lee

________________________________

**Comment by KimJorgensen** [comment]
Hi Lee,
I guess the attachments ended up in some spam filter but I found this release that could be used for testing https://csdb.dk/release/?id=159769

The latest firmware v1.14 should now support Magic Desk cartridges up to 1024kb. Let me know if it works for you.

/Kim

**Comment by Braincell1973** [comment]
Hi Kim,
              The files I made work fine now.

Thank you very much

**Comment by KimJorgensen** [comment]
Great
