### ISSUE TITLE
DFU Mode

### ISSUE THREAD

**Issue by Icelvlan88** [KimJorgensen/KungFuFlash#34]
Hello,

I cannot get my unit to go into DFU mode. I checked all my connections and I just can't get it to go. I shorted J1 and BOOT0 to 3.3v.

I also checked continuity between my usb pins and the processor. I'm not getting any voltage. I also tried using a different USB cable and no go. I tried both applications you suggested swell.

Can you give me any ideas on what I should be trying? Is there something that is supposed to be sitting between the usb cable and the PC? Using windows.

**Comment by C-64Bram** [comment]
I had the same problem. After rebooting my pc the card became visible in DFU mode. It the device is removed and reconnected ,  it sometimes becomes visible again and sometimes I have to reboot again.

**Comment by jgilcas** [comment]
Same issue here, i bought a stvlink programmer and everything works perfectly, for 2e i dont expend time to solder jumpers pins

**Comment by C-64Bram** [comment]
Like this?

https://www.st.com/en/development-tools/st-link-v2.html



Op vr 18 sep. 2020 13:09 schreef jgilcas <notifications@github.com>:

**Comment by jgilcas** [comment]
This one: https://es.aliexpress.com/item/32719963657.html?spm=a2g0s.9042311.0.0.274263c07ACJ8a

**Comment by C-64Bram** [comment]
Nice. :-)
Just ordered one. :-)



Op vr 18 sep. 2020 14:45 schreef jgilcas <notifications@github.com>:

**Comment by Icelvlan88** [comment]
I ordered one from a different vendor and receive a STC Auto Programmer USB-TTL. Will this function? Pins looks to have different names

On Sep 18, 2020, at 8:49 AM, C-64Bram <notifications@github.com> wrote:

﻿

Nice. :-)
Just ordered one. :-)



Op vr 18 sep. 2020 14:45 schreef jgilcas <notifications@github.com>:

**Comment by dikdom** [comment]
Hello,
check, if you have 5V between the J1 pin header (if it is shorted then any of its pins) and ground (shield of USB). If you have 5V check the voltage regulator whether you have the 3.3V at its output. If you have it, you should check the MCU also to have the 3.3V . Make sure the two pins of J1 and 3.3V and BOOT0 pins on J4 are shorted.
After connected everything, press the reset button of the card, it helped to be identifiable by my PC.
I used dfu-utils and the latest .upd binary to flash my card. It worked for me.
