### ISSUE TITLE
Does not work on my C-64

### ISSUE THREAD

**Issue by C-64Bram** [KimJorgensen/KungFuFlash#35]
hi! Build myself the Kung Fu Flash.  Great cartridge!! 

As described in Github I booted the device in DFU mode.
Renamed the firmware from upd to bin and used DFU file manager to create a dfu file.
Flashed the file with DefuSe and verified. No errors. So far everything ok. Removed the 2 jumpers and went to my C-64.
When I put the cartridge in the C-64, the screen stays black and the cart won"t start.
I've tried different firmwares but no result.

**Comment by jgilcas** [comment]
Could be a NTSC C64? did you check 100R array resistors?

**Comment by C-64Bram** [comment]
It's pal. Checked the array resistors and they are in place.

**Comment by jgilcas** [comment]
Could you try to use dfu-utils? there is a win64 version available, working fine with following command dfu-util -a 0 -s 0x08000000 -D KungFuFlash_v1.10.upd

**Comment by C-64Bram** [comment]
Is there a 32 bit version? I have 32 bit windows  :-)

**Comment by jgilcas** [comment]
https://sourceforge.net/projects/dfu-util/files/dfu-util-0.8-binaries/win32-mingw32/

**Comment by C-64Bram** [comment]
Thanks! Will try it later. Have to go to work now.... :-(



Op vr 18 sep. 2020 14:11 schreef jgilcas <notifications@github.com>:

**Comment by C-64Bram** [comment]
Tried with DFU-Utils. Did not work. :-( 
I quess because of the suffix because what the error sais... :-))

**Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
Cannot open DFU device 0483:df11
No DFU capable USB device available****

So I used DFU file manager to create a DFU file from the BIN -file. Strangely the created DFU file is only 336 bytes. So something is going wrong.......

**Comment by dikdom** [comment]
Hello,
with the dfu-utils I used the .upd binary what I have downloaded from here (github), without any conversation (I used linux under VirtualBox under win10).

**Comment by C-64Bram** [comment]
hi. if I load the .upd-file with DFU-utils it says "this file does not have the correct format".

**Comment by dikdom** [comment]
Hello,
this is received last time I flashed a KFF device:
~~~
~/devel$ dfu-util -a 0 -s 0x08000000 -D KungFuFlash_v1.09.upd
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Downloading to address = 0x08000000, size = 65536
Download        [=========================] 100%        65536 bytes
Download done.
File downloaded successfully
~~~

**Comment by mamejay** [comment]
Just had  a thought.  I have had this issue with the resistor ladders not being soldered in correct.  Once run over with an iron and some flux and no more black screen.  Just a thought

**Comment by C-64Bram** [comment]
Hi.
Thanks!
I am going to retry building it in a few days and also reworking the
non-working ones.

Best regards,
Bram.




Op di 5 jan. 2021 10:56 schreef mamejay <notifications@github.com>:

**Comment by medzes** [comment]
Just my 2 cents: if you get the error "No DFU capable USB device available" from dfu-utils on Windows, you probably need to install the USB driver for the ST DFU mode. The regular ST tools driver conflicts (is closed source) with what dfu-utils need. You'll need to follow the steps for example here. Short version: 
- Plug in the STM32 usb in your pc, making sure its in DFU mode
- Install Zadig

https://www.hanselman.com/blog/how-to-fix-dfuutil-stm-winusb-zadig-bootloaders-and-other-firmware-flashing-issues-on-windows

**Comment by faxm0dem** [comment]
I just had the same issue. I checked all connections on the 2 resistor networks and there was one loose solder joint. Thanks to this thread I found it right away 👍

**Comment by SunnyIMG** [comment]
Hello brother, I want to know how much thickness should be selected when making pcb

**Comment by jgilcas** [comment]
> Hello brother, I want to know how much thickness should be selected when making pcb

I'm using 1.6mm enig with golden fingers.

Regards

**Comment by SunnyIMG** [comment]
> 

thanks,bro,Does the thickness have no effect on reading?
