### ISSUE TITLE
Remote reset of C64?

### ISSUE THREAD

**Issue by mwedmark** [KimJorgensen/KungFuFlash#55]
Is there a way to remotly reset the C64 using KFF f.e. ef3 commands or other command on the command-line ?  Would be great to be able to get back to the KFF-menu/restart from any situation (that is, after starting either a prg-file or mounting a crt-file) . I guess that would need the hard reset button on the KFF to be controllable from the STM32? I'm not really sure how that works today..

**Comment by KimJorgensen** [comment]
The STM32 does control the reset line of the C64 but there is not implemented any functionality that allows you to control that via USB. I would like to keep the USB protocol compatible with EF3 but you are welcome to make your own extensions.
