### ISSUE TITLE
txt file reader?

### ISSUE THREAD

**Issue by Sebby75** [KimJorgensen/KungFuFlash#59]
Any chance to implement txt file reader into launcher/browser??

With most of my compilation .CRTs (games, utilities, etc) I have small description txt files listing what's on it, it would be handy to be able o read it before loading/flashing actual cart... I'm finding myself loading compilation .CRTs only to realise that what I'm looking for isn't there...

which brings me to another question.. what is expected write cycle count of flash memory of stm32f4 ? 1000? 5000? 10000? writes.

Regards
Seb

**Comment by KimJorgensen** [comment]
https://community.st.com/s/question/0D50X00009cga5RSAQ/stm32f405vgt7-flash-memory-write-endurance-how-many-times-can-the-internal-flash-be-written-erased

**Comment by KimJorgensen** [comment]
A text file reader has been added in the [1.46 release](https://github.com/KimJorgensen/KungFuFlash/releases/tag/v1.46)

**Comment by corasaniti** [comment]
@KimJorgensen 
I created a file with the .txt extension but from the browser I don't see it inside the folder? How can I resolve?
Thanks

**Comment by Sebby75** [comment]
![20230805_184744](https://github.com/KimJorgensen/KungFuFlash/assets/72308577/1f18cf16-a4ae-45df-8fe4-cacd85e996e8)

Seem to be working perfectly for me... created .txt file in notepad on pc moment ago and tested...
Are you sure that file is actually there??
