### ISSUE TITLE
RESET and MENU Issues

### ISSUE THREAD

**Issue by Pr0spect0r** [KimJorgensen/KungFuFlash#66]
Hello Kim

I'm enjoying your great project, thank you. 

Need your assistance, I've ordered the PCB from JLCPCB. I'm having an issue with the board where it hangs the C64, when the RESET, MENU or the RUN/STOP is pressed. Are you aware of anyone else having these issues? Is there a solution you might be aware to resolve the RESET issue?

FYI: I'm using a Breadbin C64, and I can read and run any C64 game or program without any issues, it's only when I want to reset the C64 to load another game it hangs.

Regards,
Naji

**Comment by KimJorgensen** [comment]
Hi Naji,
No, I'm not aware of anybody else having these issues.
If reset doesn't work correctly then I would check that the correct components are used for R3, R4 and Q1.

**Comment by Pr0spect0r** [comment]
Hello Kim,
Thanks for the heads-up... it was the Q1 (BC817) not functioning correct, replaced it - and all is well now. 

Keep up the great work.
