### ISSUE TITLE
Possible to use several KFF?

### ISSUE THREAD

**Issue by mwedmark** [KimJorgensen/KungFuFlash#78]
I've seen Multi-Cartridge bus adapters that can be used with C64. Would it be possible to configure and run 2 KFF at the same time in a C64 running 2 different roles? I don't know if the current of KFF*2 is too much for the C64 's Current output. Would they be able to exist on the same lines, f.e. one KFF running as a Final Cartridge (Freezer, monitor and more) and the other one as a loader for loading PRG's? There are probably other scenarios where this would be kind of cool.

**Comment by medzes** [comment]
I dont think a KFF uses much current at all.
Driving EXROM, GAME - in open-drain mode - is not going to conflict. At the same time it is not useful, as one cart will drive them one way and the other cart the other way causing issues.
Driving the datalines at the same time from both cartridges is going to be a problem.
So while theoretically possible after changing a lot of software - practically speaking this isn't feasible.
If you develop your own version of *both* cartridges then yes, they could co-exist. You probably need to figure out how to never drive datalines in parallel, how to make just one drive a menu and so on. Any misconfig would cause major issues though and be very hard to debug.

Its probably easier and less work to make your own mixed cartridge specific driver in ARM code and own adapted C64 cartridge code with the features you want, than it is to let two KFF's not conflict with each other.
