### ISSUE TITLE
EasyAPI support for EasyFlash CRTs

### ISSUE THREAD

**Issue by hackup** [KimJorgensen/KungFuFlash#8]
I would be a great improvement to the EasyFlash support if the EasyAPI for writing data to the cartridge flash and for reading it back would be implemented.

To facilitate this, the Kung Fu Flash could check for the EAPI signature and replace the code with a custom implementation when loading the CRT. (EasyProg is doing the same thing to support different flash ICs on the original hardware, if I'm not mistaken.)

To quote and include @KimJorgensen 's [first feedback](https://www.forum64.de/index.php?thread/96247-kung-fu-flash-cartridge/&postID=1486430#post1486430) on the subject:

> The biggest problem is EF emulation in 2MHz mode requires all CPU resources and thus the filesystem is shut down. The idea I had was to only write to flash and when a new selection was made then detect if the flash was changed (there is already a hash) and ask the user if the changes should be saved to a file. I guess that would be possible, except for the fact that the first 64kB of the EF image is not in flash but in RAM due to the limited flash in the microcontroller (1MB).
> 
> Another solution would be to only support this in 1MHz mode but then a method for determining whether to support 1 or 2MHz mode for a given CRT needs to be developed.

**Comment by KimJorgensen** [comment]
EasyAPI has been added to release 1.11
