### ISSUE TITLE
Kung Fu Flash not working

### ISSUE THREAD

**Issue by ref522** [KimJorgensen/KungFuFlash#84]
I purchased a Kung Fu Flash cartridge from Ebay and it doesn't boot. The led under the reset button keeps flashing. Tested it on a NTSC C64 and SX64. I ordered ST Link V2 programmer to try and re flash it. Does anyone know why the LED keeps flashing and it has a black screen on the monitor.

**Comment by gooner2077** [comment]
Have you tried cleaning the contacts on the cartridge as I had this problem with one I built and when I cleaned it it worked.
Also I would contact seller on ebay

**Comment by KimJorgensen** [comment]
Yes, please contact the seller.
I have no problems with people selling Kung Fu Flash but then they should also be willing to handle the support if something doesn't work.

**Comment by ref522** [comment]
Kim,

 I understand where you are coming from. Thanks for all your work on the product.

Richard


________________________________
