### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BrownBeanBen** [KimJorgensen/KungFuFlash#87]
so my power went out during the firmware update and now when i turn it on it just has a black screen. please help!
(btw i got my from tfw8b)

**Comment by KimJorgensen** [comment]
You should be able to use a ST-Link V2 programmer to recover, see https://github.com/KimJorgensen/KungFuFlash/blob/master/firmware/README.md. However, I'm not sure about the pinout on a TFW8b board

**Comment by KimJorgensen** [comment]
If you haven't do so, I think you should contact TFW8b for support. I'll close this issue expecting them to help you.
