### ISSUE TITLE
Scripting possibility

### ISSUE THREAD

**Issue by Gabeki17** [KimJorgensen/KungFuFlash#92]
Not sure if possible.

But if user could run scripts that would be a lot of fun!

Like if we could:

- chaining progrmams

- adding prg or crt to f keys

- cycle crt files or prg fies in an order each time rebooted
 
- change drive id for other drives, like real 1541 or even sd2iec

- load a crt then open a d64 as a drive to be able to save or open files.

All the best,
Gábor

**Comment by KimJorgensen** [comment]
Nobody seems to be willing to implement this. Closing the issue
