### ISSUE TITLE
.TAP file management

### ISSUE THREAD

**Issue by Mantics-68** [KimJorgensen/KungFuFlash#96]
Would it be possible to manage the .TAP files created by DUMP of the cassettes?

**Comment by beatmaster13** [comment]
Is it possible for KFF to capture the datassette signal and allow the cassettes to be dumped?

**Comment by KimJorgensen** [comment]
@beatmaster13 You should be able to use [EF3 utils](https://github.com/KimJorgensen/KungFuFlash/tree/master/3rd_party/ef3utils) for that. However, I must admit that I haven't tested that feature

**Comment by beatmaster13** [comment]
Thank Kim
