### ISSUE TITLE
The Final Cartridge III+ 

### ISSUE THREAD

**Issue by pietfriedrich** [KimJorgensen/KungFuFlash#97]
Hello there
Can anyone confirm that TFCIII+ crt file will work on KungFuFlash??
Regards
Piet Friedrich

**Comment by KimJorgensen** [comment]
Yes, Kung Fu Flash supports The Final Cartridge III+

**Comment by pietfriedrich** [comment]
Tak for svar…
Når jeg flasher TFCIII+ crt filen skriver den unsupoorted CRT type (29)… er der noget jeg har misset?

**Comment by KimJorgensen** [comment]
CRT type 29 is "Final Cartridge Plus" and not the same as "Final Cartridge III+" which should be is CRT type 3.

**Comment by pietfriedrich** [comment]
Thanks for your help… 💪
