### ISSUE TITLE
Porting on systems with higher clock

### ISSUE THREAD

**Issue by siriokds** [KimJorgensen/KungFuFlash#99]
Does this system can be ported to system with an higher clock (e.g. Z80 at 3.58 MHz)? What is the clock of STM32 required for this and higher clock system? STM32F411 has enough raw power to handle it?

Tnx a lot.

**Comment by KimJorgensen** [comment]
There is no simple answer to your question.

What clock speed is required is highly dependent on what your are trying to emulate and how efficient you can write that software. I.e. emulating a complex freezer cartridge requires a faster microcontroller than a emulating a simple ROM cartridge.
Also note, that the bus speed of a Z80 CPU is much lower than a 6510 CPU at the same clock speed.

I'll suggest that you do some experiments to discover what is needed for your particular application.

This issue will be closed as it is off topic.
